AWSTemplateFormatVersion: "2010-09-09"
Description: Namematching regional WAF resources

Parameters:
  pBuildNumber:
    Type: Number
  pCleanBranch:
    Type: String
    Description: The clean branch, can be used in resource names
  pCommonWafRuleGroupStackName:
    Type: String
    Description: Name of the ala-bedrock common WAF rule group stack, used to import shared rule group ARNs
  pEnvironment:
    Type: String

Conditions:
  IsProd: !Equals
    - !Ref pEnvironment
    - production
  IsDev: !Equals
    - !Ref pEnvironment
    - development


Resources:

  NamematchingWaf:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub
              - namematching-eks-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: ACL for the EKS namematching WAF
      Scope: REGIONAL
      DefaultAction:
        Allow: { }
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${pEnvironment}-namematching-DefaultAction
      Rules:
        - Name: ALAHostHeaderCheck
          Priority: 0
          Action:
            Block: {}
          Statement:
            NotStatement:
                Statement:
                  ByteMatchStatement:
                    SearchString: '.ala.org.au'
                    FieldToMatch:
                      SingleHeader:
                        Name: 'Host'
                    PositionalConstraint: ENDS_WITH
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-ALAHostHeaderCheck
        - Name: IpControl
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            RuleGroupReferenceStatement:
              Arn: !ImportValue
                Fn::Sub: ${pCommonWafRuleGroupStackName}-IpControlRuleGroupArn
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-IpControlRuleGroup
        - Name: BlockJa4Fingerprint
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            RuleGroupReferenceStatement:
              Arn: !ImportValue
                Fn::Sub: ${pCommonWafRuleGroupStackName}-BlockJa4RuleGroupArn
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-BlockJa4RuleGroup
        - Name: BlockAsn
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            RuleGroupReferenceStatement:
              Arn: !ImportValue
                Fn::Sub: ${pCommonWafRuleGroupStackName}-BlockAsnRuleGroupArn
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-BlockAsnRuleGroup
        - Name: BlockSpecificBots
          Priority: 4
          OverrideAction:
            None: {}
          Statement:
            RuleGroupReferenceStatement:
              Arn: !ImportValue
                Fn::Sub: ${pCommonWafRuleGroupStackName}-BlockSpecificBotsRuleGroupArnTmp
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-BlockSpecificBotsRuleGroup
        - Name: ALARateLimitJa4
          Action:
            Block: { }
          Priority: 5
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-ALARateLimitJa4
          Statement:
            RateBasedStatement:
              Limit: 300
              AggregateKeyType: CUSTOM_KEYS
              CustomKeys:
                - JA4Fingerprint:
                    FallbackBehavior: MATCH
              EvaluationWindowSec: 60
              ScopeDownStatement:
                NotStatement:
                  Statement:
                    GeoMatchStatement:
                      CountryCodes:
                        - AU
        - Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            None: {}
          Priority: 6
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesAmazonIpReputationList
              VendorName: AWS
              RuleActionOverrides:
               - ActionToUse:
                   Block: {}
                 Name: AWSManagedIPDDoSList
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-AWSManagedRulesAmazonIpReputationList
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesAnonymousIpList
          OverrideAction:
            None: {}
          Priority: 7
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesAnonymousIpList
              VendorName: AWS
              RuleActionOverrides:
               - ActionToUse:
                   Count: {}
                 Name: AnonymousIPList
               - ActionToUse:
                   Count: {}
                 Name: HostingProviderIPList
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-AWSManagedRulesAnonymousIpList
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            None: {}
          Priority: 8
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesKnownBadInputsRuleSet
              VendorName: AWS
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-AWSManagedRulesKnownBadInputsRuleSet
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          Priority: 9
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesCommonRuleSet
              VendorName: AWS
              RuleActionOverrides:
               - ActionToUse:
                   Count: {}
                 Name: NoUserAgent_HEADER
               - ActionToUse:
                   Count: {}
                 Name: SizeRestrictions_QUERYSTRING
               - ActionToUse:
                   Count: {}
                 Name: SizeRestrictions_BODY
               - ActionToUse:
                   Count: {}
                 Name: SizeRestrictions_URIPATH
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: true
        - Name: AWSManagedRulesBotControlRuleSet-ws
          OverrideAction:
            None: {}
          Priority: 10
          Statement:
            ManagedRuleGroupStatement:
              Name: AWSManagedRulesBotControlRuleSet
              ManagedRuleGroupConfigs:
                - AWSManagedRulesBotControlRuleSet:
                    EnableMachineLearning: FALSE
                    InspectionLevel: COMMON
              VendorName: AWS
              RuleActionOverrides:
               - ActionToUse:
                   Count: {}
                 Name: CategoryHttpLibrary
               - ActionToUse:
                   Allow: {}
                 Name: CategoryLinkChecker
               - ActionToUse:
                   Allow: {}
                 Name: CategoryMonitoring
               - ActionToUse:
                   Count: {}
                 Name: SignalAutomatedBrowser
               - ActionToUse:
                   Count: {}
                 Name: SignalNonBrowserUserAgent
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-AWSManagedRulesBotControlRuleSet-ws
            SampledRequestsEnabled: true
        - Name: ALARateLimitGoodBots
          Action:
            Block: { }
          Priority: 11
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-ALARateLimitGoodBots
          Statement:
            RateBasedStatement:
              Limit: 120
              AggregateKeyType: CONSTANT
              EvaluationWindowSec: 60
              ScopeDownStatement:
                LabelMatchStatement:
                  Key: bot:verified
                  Scope: LABEL
        - Name: ALABlockDatacenterBrowsers
          Action:
            Block: {}
          Priority: 12
          RuleLabels:
            - Name: bot:datacenterbrowsers
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${pEnvironment}-namematching-ALABlockDatacenterBrowsers
          Statement:
            AndStatement:
              Statements:
                - NotStatement:
                    Statement:
                      GeoMatchStatement:
                        CountryCodes:
                          - AU
                          - NZ
                - NotStatement:
                    Statement:
                      ByteMatchStatement:
                        SearchString: '/ws'
                        FieldToMatch:
                          UriPath: {}
                        PositionalConstraint: STARTS_WITH
                        TextTransformations:
                          - Priority: 0
                            Type: NONE
                - LabelMatchStatement:
                    Key: 'awswaf:managed:aws:anonymous-ip-list:HostingProviderIPList'
                    Scope: LABEL
                - NotStatement:
                    Statement:
                      LabelMatchStatement:
                        Key: 'awswaf:managed:aws:bot-control:signal:non_browser_user_agent'
                        Scope: LABEL
                - NotStatement:
                    Statement:
                      LabelMatchStatement:
                        Key: 'awswaf:managed:aws:bot-control:bot:'
                        Scope: NAMESPACE

  NamematchingLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt NamematchingWaf.Arn
      LogDestinationConfigs:
        - !GetAtt NamematchingWafLogGroup.Arn

  NamematchingWafLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub
                       - aws-waf-logs-${pEnvironment}/${NamematchingWafName}-ia
                       - NamematchingWafName: !Select [ 0, !Split [ '|', !Ref NamematchingWaf]]
      LogGroupClass: INFREQUENT_ACCESS
      RetentionInDays: 14
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

Outputs:
  NamematchingWafArn:
    Description: The ARN of the WAF
    Value: !GetAtt NamematchingWaf.Arn
