[DEFAULT]
PRODUCT_NAME = namematching-service

AUTO_DEPLOY = true
GITHUB_REPO_NAME = ala-namematching-service
GITHUB_OWNER = AtlasOfLivingAustralia
REGION = ap-southeast-2
ALLOW_TEARDOWN = true

# the bootstrap stack names. These are used by the codepipeline stacks to import
# the codepipeline roles, buckets and codestar connections
BOOTSTRAP_STACK_NAME = ala-bedrock-cicd-bootstrap-production
BUCKETS_STACK_NAME = ala-bedrock-cicd-buckets-production
VPC_STACK_NAME = ala-bedrock-vpc-production

# the app stacks — no base stack for namematching (stateless, no AWS service dependencies)
ECR_STACK_NAME = ala-${PRODUCT_NAME}-ecr-${ENVIRONMENT}
WAF_STACK_NAME = ala-${PRODUCT_NAME}-waf-${ENVIRONMENT}
# used to pull in common Bedrock WAF rules
COMMON_WAF_RULE_GROUP_STACK_NAME = ala-bedrock-waf-common-waf-rule-group-production

ALA_SECRETS_NAME = ala-secrets-production

IMAGE_NAME = ala-namematching-service
IMAGE_TAG = latest

WS_SUB_DOMAIN = namematching-ws
INTERNAL_WS_SUB_DOMAIN = namematching-internal-ws

[development]
ECR_STACK_NAME = ala-${PRODUCT_NAME}-ecr-${CLEAN_BRANCH}
WAF_STACK_NAME = ala-${PRODUCT_NAME}-waf-${CLEAN_BRANCH}
COMMON_WAF_RULE_GROUP_STACK_NAME = ala-bedrock-waf-common-waf-rule-group-testing

HOSTED_ZONE = dev.ala.org.au
INTERNAL_HOSTED_ZONE = dev.ala.org.au

APP_CERTIFICATE = arn:aws:acm:ap-southeast-2:748909248546:certificate/969309c3-9c24-4fc8-9e16-10334e82bbd4

REGOLITH_STACK_NAME = ala-regolith-cluster-testing

WS_SUB_DOMAIN = namematching-${CLEAN_BRANCH}-ws
INTERNAL_WS_SUB_DOMAIN = namematching-${CLEAN_BRANCH}-internal-ws

[testing]
ALLOW_TEARDOWN = true

COMMON_WAF_RULE_GROUP_STACK_NAME = ala-bedrock-waf-common-waf-rule-group-testing

HOSTED_ZONE = test.ala.org.au
INTERNAL_HOSTED_ZONE = test.ala.org.au

APP_CERTIFICATE = arn:aws:acm:ap-southeast-2:748909248546:certificate/506d78ff-d909-4c89-8cc7-660a30305982

REGOLITH_STACK_NAME = ala-regolith-cluster-testing

WS_SUB_DOMAIN = namematching-ws
INTERNAL_WS_SUB_DOMAIN = namematching-internal-ws

[staging]
HOSTED_ZONE = ala.org.au
INTERNAL_HOSTED_ZONE = ala.org.au

APP_CERTIFICATE = arn:aws:acm:ap-southeast-2:736913556139:certificate/efa73382-d34b-4091-a918-a303333e7a4c

REGOLITH_STACK_NAME = ala-regolith-cluster-production

WS_SUB_DOMAIN = namematching-staging-ws
INTERNAL_WS_SUB_DOMAIN = namematching-staging-internal-ws

[production]
AUTO_DEPLOY = false
ALLOW_TEARDOWN = false

HOSTED_ZONE = ala.org.au
INTERNAL_HOSTED_ZONE = ala.org.au

APP_CERTIFICATE = arn:aws:acm:ap-southeast-2:736913556139:certificate/efa73382-d34b-4091-a918-a303333e7a4c

REGOLITH_STACK_NAME = ala-regolith-cluster-production

WS_SUB_DOMAIN = namematching-ws
INTERNAL_WS_SUB_DOMAIN = namematching-internal-ws

