logging:
  level: INFO
  loggers:
    au.org.ala: WARN
    org.reflections: ERROR
server:
  applicationConnectors:
    - type: http
      port: 9279
      outputBufferSize: 32KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
  adminConnectors:
    - type: http
      port: 9280
search:
  index: /data/lucene/namematching-20210811-2
  groups: file:src/main/resources/groups.json
  subgroups: file:src/main/resources/subgroups.json
  cache:
    entryCapacity: 1000
    enableJmx: true
