# https://www.debian.org/doc/manuals/maint-guide/dother.en.html#install
server/src/main/resources/subgroups.json data/ala-namematching-service/config/
server/src/main/resources/groups.json data/ala-namematching-service/config/
server/target/ala-namematching-server.jar opt/atlas/ala-namematching-service/
# TODO: we should move this to other location and with other name referencing to this service
server/config.yml data/ala-namematching-service/config/
